### ISSUE TITLE
Lookbook stalls out while rendering

### ISSUE THREAD

**Issue by trappar** [allmarkedup/lookbook#135] opened 2022-09-06 20:51 UTC
Hey, I just upgraded to 1.0.3 and I'm seeing a new issue that just popped up. Some of the time (not 100%) while rendering lookbook, it stalls out and completely locks up my server. I've managed to capture the same request twice, once where it stalls and once where it doesn't. Hopefully this helps identify where the issue is coming from. This seems to happen pretty frequently. I can load lookbook and refresh 5-10 times and usually one of those will stall. Seems like a race condition of some type. Here are the logs:

This request went just fine:
```bash
Started GET "/lookbook/inspect/[redacted]" for 127.0.0.1 at 2022-09-06 20:42:51 +0000	
  ActiveRecord::SchemaMigration Pluck (0.2ms)  SELECT `schema_migrations`.`version` FROM `schema_migrations` ORDER BY `schema_migrations`.`version` ASC	
Processing by Lookbook::PreviewsController#show as HTML	
  Parameters: {"path"=>"[redacted]"}	
Processing by ViewComponentsController#render_example_to_string as HTML	
  Parameters: {"path"=>"[redacted]"}	
  Rendering /gems/gems/view_component-2.71.0/app/views/view_components/preview.html.erb	
  Rendered /gems/gems/view_component-2.71.0/app/views/view_components/preview.html.erb (Duration: 17.8ms | Allocations: 24682)	
  Rendering html template	
  Rendered html template (Duration: 0.0ms | Allocations: 13)	
Completed 200 OK in 22ms (Views: 0.9ms | ActiveRecord: 1.5ms | Allocations: 29233)	
  Rendering layout /gems/gems/lookbook-1.0.3/app/views/layouts/lookbook/inspector.html.erb	
  Rendering /gems/gems/lookbook-1.0.3/app/views/lookbook/previews/show.html.erb within layouts/lookbook/inspector	
  Rendered /gems/gems/lookbook-1.0.3/app/views/lookbook/previews/panels/_preview.html.erb (Duration: 1.3ms | Allocations: 1565)	
  Rendered /gems/gems/lookbook-1.0.3/app/views/lookbook/previews/panels/_output.html.erb (Duration: 61.8ms | Allocations: 89377)	
  Rendered /gems/gems/lookbook-1.0.3/app/views/lookbook/previews/panels/_source.html.erb (Duration: 1.2ms | Allocations: 1669)	
  Rendered /gems/gems/lookbook-1.0.3/app/views/lookbook/previews/panels/_notes.html.erb (Duration: 1.4ms | Allocations: 1364)	
  Rendered /gems/gems/lookbook-1.0.3/app/views/lookbook/previews/panels/_params.html.erb (Duration: 0.5ms | Allocations: 574)	
  Rendered /gems/gems/lookbook-1.0.3/app/views/lookbook/previews/show.html.erb within layouts/lookbook/inspector (Duration: 115.6ms | Allocations: 143555)	
  Rendering /gems/gems/lookbook-1.0.3/app/views/layouts/lookbook/application.html.erb	
  Rendering /gems/gems/lookbook-1.0.3/app/views/layouts/lookbook/shell.html.erb	
  Rendering /gems/gems/lookbook-1.0.3/app/views/layouts/lookbook/skeleton.html.erb	
  Rendered /gems/gems/lookbook-1.0.3/app/views/layouts/lookbook/skeleton.html.erb (Duration: 1.2ms | Allocations: 1551)	
  Rendered /gems/gems/lookbook-1.0.3/app/views/layouts/lookbook/shell.html.erb (Duration: 5.7ms | Allocations: 7490)	
  Rendered /gems/gems/lookbook-1.0.3/app/views/layouts/lookbook/application.html.erb (Duration: 184.4ms | Allocations: 240100)	
  Rendered layout /gems/gems/lookbook-1.0.3/app/views/layouts/lookbook/inspector.html.erb (Duration: 301.3ms | Allocations: 385951)	
Completed 200 OK in 428ms (Views: 301.9ms | ActiveRecord: 0.0ms | Allocations: 644331)	
Started GET "/lookbook-assets/css/lookbook.css?v=1.0.3" for 127.0.0.1 at 2022-09-06 20:42:52 +0000	
Started GET "/lookbook-assets/js/lookbook.js?v=1.0.3" for 127.0.0.1 at 2022-09-06 20:42:52 +0000	
Started GET "/lookbook-assets/css/themes/indigo.css?v=1.0.3" for 127.0.0.1 at 2022-09-06 20:42:52 +0000	
Started GET "/lookbook/preview/[redacted]?lookbook_timestamp=2022-09-06+20%3A42%3A51+%2B0000" for 127.0.0.1 at 2022-09-06 20:42:52 +0000	
Processing by Lookbook::PreviewsController#preview as HTML	
  Parameters: {"lookbook_timestamp"=>"2022-09-06 20:42:51 +0000", "path"=>"[redacted]"}	
Processing by ViewComponentsController#render_example_to_string as HTML	
  Parameters: {"lookbook_timestamp"=>"2022-09-06 20:42:51 +0000", "path"=>"[redacted]"}	
  Rendering /gems/gems/view_component-2.71.0/app/views/view_components/preview.html.erb	
  Rendered /gems/gems/view_component-2.71.0/app/views/view_components/preview.html.erb (Duration: 10.7ms | Allocations: 14947)	
  Rendering html template	
  Rendered html template (Duration: 0.0ms | Allocations: 7)	
Completed 200 OK in 14ms (Views: 1.5ms | ActiveRecord: 0.0ms | Allocations: 17564)	
Processing by ViewComponentsController#render_in_layout_to_string as HTML	
  Parameters: {"lookbook_timestamp"=>"2022-09-06 20:42:51 +0000", "path"=>"[redacted]"}	
  Rendering layout layouts/component_preview.html.haml	
  Rendering /gems/gems/lookbook-1.0.3/app/views/lookbook/preview.html.erb within layouts/component_preview	
  Rendered /gems/gems/lookbook-1.0.3/app/views/lookbook/preview.html.erb within layouts/component_preview (Duration: 1.1ms | Allocations: 577)	
Started GET "/lookbook-assets/feather-sprite.svg" for 127.0.0.1 at 2022-09-06 20:42:52 +0000	
Started GET "/lookbook/lookbook-cable?uid=1662496972521" for 127.0.0.1 at 2022-09-06 20:42:52 +0000	
  Rendered shared/_head_common.html.haml (Duration: 199.7ms | Allocations: 249524)	
  Rendered layout layouts/component_preview.html.haml (Duration: 205.5ms | Allocations: 254715)	
  Rendering html template	
  Rendered html template (Duration: 0.0ms | Allocations: 7)	
Completed 200 OK in 209ms (Views: 1.0ms | ActiveRecord: 0.0ms | Allocations: 257898)	
  Rendering html template	
  Rendered html template (Duration: 0.0ms | Allocations: 4)	
Completed 200 OK in 231ms (Views: 0.9ms | ActiveRecord: 0.0ms | Allocations: 293395)
```

And here's an example of a request that stalled my server

```bash
Started GET "/lookbook/inspect/[redacted]" for 127.0.0.1 at 2022-09-06 20:43:42 +0000
Processing by Lookbook::PreviewsController#show as HTML
  Parameters: {"path"=>"[redacted]"}
Processing by ViewComponentsController#render_example_to_string as HTML
  Parameters: {"path"=>"[redacted]"}
  Rendering /gems/gems/view_component-2.71.0/app/views/view_components/preview.html.erb
Started GET "/lookbook/lookbook-cable?uid=1662497022169" for 127.0.0.1 at 2022-09-06 20:43:42 +0000
  Rendered /gems/gems/view_component-2.71.0/app/views/view_components/preview.html.erb (Duration: 16.1ms | Allocations: 16228)
  Rendering html template
  Rendered html template (Duration: 0.0ms | Allocations: 9)
Completed 200 OK in 19ms (Views: 0.7ms | ActiveRecord: 0.0ms | Allocations: 18961)


  Rendering layout /gems/gems/lookbook-1.0.3/app/views/layouts/lookbook/inspector.html.erb
  Rendering /gems/gems/lookbook-1.0.3/app/views/lookbook/previews/show.html.erb within layouts/lookbook/inspector
  Rendered /gems/gems/lookbook-1.0.3/app/views/lookbook/previews/panels/_preview.html.erb (Duration: 0.9ms | Allocations: 895)
  Rendered /gems/gems/lookbook-1.0.3/app/views/lookbook/previews/panels/_output.html.erb (Duration: 4.5ms | Allocations: 8706)
Started GET "/lookbook/inspect/[redacted]" for 127.0.0.1 at 2022-09-06 20:43:42 +0000
Processing by Lookbook::PreviewsController#show as HTML
  Parameters: {"path"=>"[redacted]"}
Processing by ViewComponentsController#render_example_to_string as HTML
  Parameters: {"path"=>"[redacted]"}
  Rendering /gems/gems/view_component-2.71.0/app/views/view_components/preview.html.erb
  Rendered /gems/gems/view_component-2.71.0/app/views/view_components/preview.html.erb (Duration: 11.3ms | Allocations: 15147)
  Rendering html template
  Rendered html template (Duration: 0.0ms | Allocations: 7)
Completed 200 OK in 14ms (Views: 1.0ms | ActiveRecord: 0.2ms | Allocations: 17753)


  Rendering layout /gems/gems/lookbook-1.0.3/app/views/layouts/lookbook/inspector.html.erb
  Rendering /gems/gems/lookbook-1.0.3/app/views/lookbook/previews/show.html.erb within layouts/lookbook/inspector
```

And it just hangs there forever.

This has been confirmed by multiple members of my team. Please let me know what other information I can get you to help diagnose the bug.

**Comment by allmarkedup** [comment] 2022-09-06 21:59
Hi @trappar, many thanks for the detailed info - I've actually just started running into this issue occasionally myself but haven't had a chance to dig into it properly yet. I will hopefully get a chance to look at it tomorrow (UK time) and will get a fix together as soon as I can figure out what is causing it.

**Comment by allmarkedup** [comment] 2022-09-08 09:53
Hey @trappar - I believe I've got (at least a partial) fix for this issue. Could you try installing the gem from the `fix-hanging-server` branch and let me know if you are still seeing the same problem?

```rb
gem 'lookbook', git: 'git://github.com/allmarkedup/lookbook.git', branch: 'fix-hanging-server'
```

As a nice side effect the changes seem to have sped up performance a bit too. I'm cautious to say the issue has been fully resolved as I couldn't find a way to reliably reproduce it 100% of the time but from my testing so far I'm not seeing the same problem after these updates.

If you could let me know how you get on with it that would be much appreciated.

**Comment by trappar** [comment] 2022-09-08 16:59
Nope, still freezing for me the same way.

**Comment by allmarkedup** [comment] 2022-09-09 08:13
@trappar Ok, thanks for letting me know - I'll hopefully get some time this weekend to try and figure out how to reliably recreate the issue so I can see what else might be causing it.

Out of interest, (roughly) how many viewcomponents do you have in your project?

**Comment by trappar** [comment] 2022-09-09 17:17
Around 35 at the moment.

**Comment by allmarkedup** [comment] 2022-09-13 21:36
Hey @trappar, I just wanted to give you an update with where I'm at with this issue.

I've just released a new version that contains a bunch of fixes for various issues, including a few that should definitely help to mitigate the issue you are seeing - or at least they do in my local testing. However I've not been able to eliminate it completely, it seems to be a problem with concurrent requests that cause the server to hang but I've not been able to figure out quite why yet.

After a lot of digging about and referencing other similar issues opened on the Rails repo I've found that setting the `RAILS_MAX_THREADS` environment variable to `1` locally (to restrict Puma to a single thread per worker) eliminates the issue altogether. 

Whilst I appreciate this isn't a proper fix it may be worth trying if you are still running into the issue after updating to the latest release to at least eliminate some of the frustration. And of course if I make any more progress on actually tracking down the root cause of the issue I'll let you know.

**Comment by allmarkedup** [comment] 2022-09-16 14:22
@trappar after some more digging I believe this issue may actually be related to [a deadlock issue](https://github.com/ViewComponent/view_component/issues/1488) in ViewComponent.

Downgrading ViewComponent to version `2.63.0` seems to help fix the problem for me so you may want to try that instead of the `RAILS_MAX_THREADS` option.

**Comment by trappar** [comment] 2022-09-16 23:45
@allmarkedup Hm, yeah I just tried upgrading to lookbook @ `1.0.8` and tried different versions of ViewComponent. Here's what I got:
* ViewComponent @ `2.71.0` - Locks up easily
* ViewComponent @ `2.63.0` - Could not get it to lock up even after probably around 100 refreshes

So I definitely think you're on to something here...

**Comment by allmarkedup** [comment] 2022-09-17 11:27
@trappar ok thanks, appreciate you taking the time to test and confirm. Hopefully we can get the issue resolved soon!

**Comment by stevegeek** [comment] 2022-09-21 13:58
Just chiming in here to say just update ViewComponent to `2.71.0` too and seeing the same as @trappar . Thanks for looking into it so far @allmarkedup !

**Comment by allmarkedup** [comment] 2022-09-21 14:11
@stevegeek Ok thanks for letting me know - I don't know how quickly a fix is coming so for now I'd recommend using ViewComponent `2.63.0` until it's fixed upstream or I have a better workaround at the Lookbook end.

**Comment by Spone** [comment] 2022-10-08 11:22
Hi @stevegeek @trappar! [A fix is coming](https://github.com/ViewComponent/view_component/pull/1550) to ViewComponent, can you please try it out and confirm if it's working for you? See here: https://github.com/ViewComponent/view_component/issues/1488#issuecomment-1272102196

**Comment by stevegeek** [comment] 2022-10-08 14:17
Seems to have solved the issue!

**Comment by allmarkedup** [comment] 2022-10-08 20:35
Thanks for updating here @Spone. As the PR in the ViewComponent repo seems to fix the problem I'm going to go ahead and close this issue now. Of course if anyone still runs into any Lookbook-specific issues once the fix is released then please let me know and I'll look into it again.

**Closed by allmarkedup** 2022-10-08 20:35 UTC
Labels: bug

**Comment by Spone** [comment] 2022-10-10 22:57
[v2.74.1](https://github.com/ViewComponent/view_component/releases/tag/v2.74.1) has been released, please try it out!
